

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  TARGET_VAR: "quality"
  ALPHA: 0.9
  L1_RATIO: 0.9
  RANDOM_STATE: 42

jobs:
  build:
    strategy:
     matrix:
       os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
#     runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Setup Python xx
      - name: Set up Python sss
        uses: actions/setup-python@v1.2.1
        with:
          python-version: "3.8"
      
      # Check Env Variables
      - name: Check Env
        run: |
          echo $CSV_URL

      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow
      
      # Run as a mlflow project
      - name: Run mlflow project
        run: |
          mlflow run wine_example --env-manager=local
